### PR TITLE
fix newBot return

### PR DESCRIPTION
**Pull request by deepoil**
Hi,
Sorry for being late.
Fixed the return value of function NewBot. 
In addition, other corrections are also pushed together.

### CODE REVIEW

**Comment by oklahomer** [comment]
@deepoil Thank you for creating a new pull request regarding the work introduced in #109.
As we discussed in your previous pull request, your work addresses a couple of different issues.
One can improve `sarah.NewBot()` with a breaking interface change; the other one can improve the internal of `defaultUserContextStorage.Get()` without any interface change.

In general, a pull request should address only one issue at a time.
So I did not expect to have "other corrections are also pushed" when you said "I would like to send a pull request for the sarah.NewBot() changes to it" in #109. ( I would say "improve" instead of "corrections," by the way. )

Regarding this particular work, I suppose one pull request toward `v4-dev` can address `sarah.NewBot()` while another one toward `master` can address `defaultUserContextStorage.Get()` improvement.

**Comment by oklahomer** [comment]
Hi, @deepoil 
Do we have any update on this?

**Comment by deepoil** [comment]
@oklahomer 
I'm sorry I'm so late.
Rolled back `defaultUserContextStorage.Get()`.
Now the changes are only related to `NewBot()`.
Was it all right?

**Review by oklahomer — APPROVED** [review]
Thank you for your work.
Now this looks good 👍

**Comment by deepoil** [comment]
@oklahomer 
Thank you. I'm sorry I'm late this time.

**Pull request merged**
